apiVersion: v1
kind: Service
metadata:
  name: aws-webapp
  namespace: multicloud
spec:
  type: ExternalName
  externalName: web-app.multicloud.svc.cluster.local
  ports:
  - port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: aws-app-direct
  namespace: multicloud
subsets:
- addresses:
  - ip: 172.18.255.201
  ports:
  - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aws-app-direct
  namespace: multicloud
spec:
  ports:
  - port: 80
    targetPort: 80




